name = "SymbolicAnalysis"
uuid = "4297ee4d-0239-47d8-ba5d-195ecdf594fe"
authors = ["Vaibhav Dixit <vaibhavyashdixit@gmail.com>", "Shashi Gowda <gowda@mit.edu>"]
version = "0.3.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
DataStructures = "0.18"
Dictionaries = "0.4"
Distributions = "0.25"
DomainSets = "0.7"
DSP = "0.7"
IfElse = "0.1"
Manifolds = "0.9"
LinearAlgebra = "1.10"
LogExpFunctions = "0.3"
PDMats = "0.11"
RecursiveArrayTools = "3"
StatsBase = "0.34"
Symbolics = "6"
SymbolicUtils = "3"
julia = "1.10"

